### ISSUE TITLE
Unimplemented element at 10:

### ISSUE THREAD

**Issue by iamphill** [boxen/puppet-sublime_text_2#11]
Keep getting the following error when running script/boxen

Could not set 'present' on ensure: Unimplemented element at 10:/Users/[USER]/src/my-boxen/shared/sublime_text_2/manifests/init.pp

**Comment by wfarr** [comment]
What version of the sublime text 2 module?

**Comment by iamphill** [comment]
1.1.2

**Comment by wfarr** [comment]
How odd. Seems like a provider is missing... But that should be built in to Puppet.

**Comment by iamphill** [comment]
Closed issue. Think it was just my laptop playing up, got new mac over weekend and works fine.
