### ISSUE TITLE
Modified Bindir

### ISSUE THREAD

**Issue by rhoml** [boxen/puppet-sublime_text_2#2]
I´ve modified bindir because the subl shortcut wasn´t working on mountain lion https://github.com/rhoml/puppet-sublime_text_2/blob/master/manifests/init.pp

**Comment by ocxo** [comment]
@rhoml Thanks for this! Can you put in a proper pull request and we'll try to get it merged?

**Comment by ocxo** [comment]
@rhoml bump

**Comment by ocxo** [comment]
Closing. Will wait for PR from @rhoml.
