### ISSUE TITLE
No Tagged branch with Sublime Package functionality

### ISSUE THREAD

**Issue by apackeer** [boxen/puppet-sublime_text_2#7]
Eager to try out the new Package functionality, but there is no tagged branch. My Puppet file has:

```
github "sublime_text_2",        "1.1.0"
```

Is there a tagged branch that I can use with this new functionality?

**Comment by ocxo** [comment]
Here's tag 1.1.1 https://github.com/boxen/puppet-sublime_text_2/tree/1.1.1
