### ISSUE TITLE
New ST3 Beta repo

### ISSUE THREAD

**Issue by slantview** [boxen/puppet-sublime_text_2#8]
I forked this and created a repo at https://github.com/slantview/puppet-sublime_text to be able to use the Beta builds from [Sublime Text](http://www.sublimetext.com/3).  Can we get this added to boxen?

Best,

Steve

**Comment by MoOx** [comment]
Thanks for this repo.

Requests have to be made here https://github.com/boxen/our-boxen/issues?state=open
